-- Table: starrs.GRAD_APPLICATION

-- DROP TABLE IF EXISTS starrs."GRAD_APPLICATION";

CREATE TABLE IF NOT EXISTS starrs."GRAD_APPLICATION"
(
    "APPLICATION_ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "USER_ID" character varying(10) COLLATE pg_catalog."default",
    "STATUS" character varying(10) COLLATE pg_catalog."default",
    "DECISION_DATE" date,
    "DECISION" character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT "GRAD_APPLICATION_pkey" PRIMARY KEY ("APPLICATION_ID"),
    CONSTRAINT "GRAD_APPLICATION_STUDENT_ID_fkey" FOREIGN KEY ("USER_ID")
        REFERENCES starrs."USER" ("USER_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS starrs."GRAD_APPLICATION"
    OWNER to postgres;